/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/4sepbrainwithouttex.glb");

  const ref = useRef();

  useFrame((state, delta) => (ref.current.rotation.y += 0.005));

  return (
    <group {...props} dispose={null} scale={0.02} ref={ref}>
      <mesh
        geometry={nodes.right_front.geometry}
        material={nodes.right_front.material}
      >
        <meshStandardMaterial color={"hotpink"} />
      </mesh>
      <mesh
        geometry={nodes.right_back.geometry}
        material={nodes.right_back.material}
      />
      <mesh
        geometry={nodes.mybrain003.geometry}
        material={nodes.mybrain003.material}
      />
      <lineSegments
        geometry={nodes.mybrain003_1.geometry}
        material={nodes.mybrain003_1.material}
      />
      <mesh
        geometry={nodes.left_back.geometry}
        material={nodes.left_back.material}
      />
    </group>
  );
}

useGLTF.preload("/4sepbrainwithouttex.glb");
